### ISSUE TITLE
不能并发连接的bug

### ISSUE THREAD

**Issue by TCLP** [idlewalker/open_service#1]
问题：server.c +171 channel_t conn;是一个栈变量，传到线程中之后就会被回收掉。
改进：channel_t *conn = NULL;定义到while循环外面，在每次循环的时候conn = malloc(...)，在线程中使用栈变量接受conn之后free掉内存。

**Comment by hair-man** [comment]
while不停的重新创建和释放conn，有可能地址也都是一样的，导致多个线程用的同一个地址的可能性
